live_share_youtube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles import views
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('player.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]

player/urls.py
from django.urls import path
from . import views

app_name = "player"
urlpatterns = [
    path('<int:token>', views.playlist, name='playlist'),
    path('remove/<int:pk>', views.remove_link, name='remove-link'),
    path('<int:token>/add', views.add_link, name='add'),
    path('<int:token>/list', views.get_list, name='list'),
    path('new', views.new_playlist, name='new'),
    path('', views.all_playlist, name='all'),
]

player/models.py
import requests
import json

from django.db import models
from django.shortcuts import reverse

PK_LENGTH = 23
YOUTUBE_INFO_URL = 'http://www.youtube.com/oembed?url=http://www.youtube.com/watch?v={}&format=json'

class Playlist(models.Model):
    date = models.DateTimeField(verbose_name="date")
    name = models.CharField(
        max_length=255,
        verbose_name="Nom de la playlist"
    )
    last_update = models.DateTimeField(
        verbose_name="Dernière mise à jour"
    )
    last_get = models.DateTimeField(
        verbose_name="Dernière écoute"
    )
    public = models.BooleanField(
        verbose_name="Visible sur la page d'accueil",
        default=True,
    )

    @staticmethod
    def reverse_token(token):
        return token & ((1 << PK_LENGTH) - 1)

    def get_token(self):
        return int(self.date.timestamp()) << PK_LENGTH | self.pk

    def get_absolute_url(self):
        return reverse('player:playlist', kwargs={'token':self.get_token()})

    def __str__(self):
        return "Playlist " + str(self.get_token())


class Link(models.Model):
    token = models.CharField(
        max_length=200,
        verbose_name="Token",
    )
    playlist = models.ForeignKey(
        Playlist,
        on_delete=models.CASCADE,
        verbose_name="Playlist",
    )
    title = models.CharField(
        max_length=255,
        verbose_name="Titre"
    )


    def __str__(self):
        return "Link : " + self.token + " of " + str(self.playlist)

    @classmethod
    def update_titles(cls):
        for o in cls.objects.all():
            response = requests.get(YOUTUBE_INFO_URL.format(o.token))
            o.title = json.loads(response.content.decode('utf-8'))['title']
            o.save()

player/forms.py
from urllib.parse import urlparse, parse_qs

import django.utils.timezone as timezone
from django import forms

from player.models import Playlist, Link


class PlaylistForm(forms.ModelForm):
    class Meta:
        model = Playlist
        fields = ['name', 'public']

    def is_valid(self):
        self.instance.date = timezone.now()
        self.instance.last_get = timezone.now()
        self.instance.last_update = timezone.now()
        return super().is_valid()

class LinkForm(forms.Form):
    url = forms.URLField(label="URL de la piste à ajouter")

    def get_token(self):
        p=urlparse(self.cleaned_data['url'])
        p = parse_qs(p.query)
        return p['v'][0]

player/views.py
import json
import requests

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize
import django.utils.timezone as timezone

from player.models import Playlist, Link, YOUTUBE_INFO_URL
from player.forms import PlaylistForm, LinkForm




def new_playlist(request):
    p = PlaylistForm(request.POST or None)
    if p.is_valid():
        playlist = p.save()
        return redirect(playlist.get_absolute_url())
    return render(request, 'form.html', {
        'form':p,
        'validate':'Créer',
        'title':'Nouvelle playlist'
    })


@csrf_exempt
def get_list(request, token):
    p = get_object_or_404(Playlist, pk=Playlist.reverse_token(token))
    p.last_get = timezone.now()
    p.save()

    d = {'tokens':[], 'updated':False}
    print(p.last_update.timestamp(),int(request.GET.get('last_sync', 0))/1000)
    print(p.last_update.timestamp() >= int(request.GET.get('last_sync', 0))/1000)


    if p.last_update.timestamp() >= int(request.GET.get('last_sync', 0))/1000:
        d['updated'] = True
        d['videos'] = [
            {'token':l.token, 'title':l.title} for l in p.link_set.all()
        ]
    return HttpResponse(json.dumps(d), content_type='application/json')


@csrf_exempt
def add_link(request, token):
    p = get_object_or_404(Playlist, pk=Playlist.reverse_token(token))
    l = LinkForm(request.POST or None)
    if l.is_valid():
        yt_token = l.get_token()
        response = requests.get(YOUTUBE_INFO_URL.format(yt_token))
        try:
            q = json.loads(response.content.decode('utf-8'))
            title = q['title']
        except KeyError:
            title = "Je n'arrive pas à retrouver le titre :("
        p.last_update = timezone.now()
        p.save()
        link = Link()
        link.token = yt_token
        link.title = title
        link.playlist = p
        link.save()
        return HttpResponse('Ok')
    return render(request, 'form_inline.html', {
        'form':l,
        'validate':'Ajouter'
    })


def remove_link(request, pk):
    l = get_object_or_404(Link, pk=pk)
    l.delete()
    return HttpResponse('Ok')


def playlist(request, token):
    p = get_object_or_404(Playlist, pk=Playlist.reverse_token(token))
    add_link_form = LinkForm()
    return render(request, 'player/playlist.html', {
        'playlist':p,
        'form':add_link_form
    })


def all_playlist(request):
    p = Playlist.objects.filter(public=True).order_by('date')
    return render(request, 'player/all_list.html', {'lists':p})

player/templates/player/all_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-md-6 text-justify">
		<h1>Live Share</h1>
		<br/>
		<p>Bienvenue sur Live Share. Vous pouvez créer des playlist youtube anonymes, collaboratives et éphémères !</p>
		<br/>
		<br/>
		<a class="btn btn-success btn-lg" type='button' href="{% url 'player:new' %}">
			<i class="fa fa-plus"></i> Nouvelle playlist
		</a>
		<br/>
		<br/>
	</div>
	<div class="col-md-6 text-justify">
		<h1>Diffusions en cours</h1>
		<br/>
		{% for l in lists %}
		<a class="card bg-secondary text-white" href="{{l.get_absolute_url}}">
			<div class="card-body">
				<i class="far fa-play-circle"></i>
				{{l.name}}
			</div>
		</a>
		<br/>
		{% endfor %}
</div>
{% endblock %}

player/templates/player/playlist.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block title %} - {{playlist.name}}{% endblock %}

{% block js %}<script src="{% static "js/playlist.js" %}"></script>{% endblock %}

{% block content %}
	<script>
	var tracks = [{% for link in playlist.link_set.all %}
	"{{link.token}}",
	{% endfor %}];
    var add_url = "{% url 'player:add' playlist.get_token %}";
	var get_url = "{% url 'player:list' playlist.get_token %}";
	$(document).ready(function(){
	    $(window).resize(function(){
			$("#links").height($('#player').height());
	    });
	});
    </script>

	<div class="row" style="height:100%">
		<div class="col-md-6">
			<h1>{{playlist.name}}</h1>
			<div class="row">
				<div class="col-md-10">
					<h2>Lecture</h2>
				</div>
				<div class="col-md-2">
					<div class="btn-group">
						<a class="btn btn-outline-dark" role="button" onclick="prev();">
							<i class="fas fa-step-backward"></i>
						</a>
						<a class="btn btn-outline-dark" role="button" onclick="next();">
							<i class="fas fa-step-forward"></i>
						</a>
					</div>
				</div>
			</div>
			<!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
			<div id="player" style="max-width:100%"></div>
		</div>
		<div class="col-md-6">
			<h2>Pistes à venir</h2>
			<div id="links" style="overflow-y:scroll;">
			{% for link in playlist.link_set.all %}
			<div class="card bg-secondary text-white" onclick="setCurrent(parseInt(this.id));" id="{{ forloop.counter0 }}">
				<div class="card-body">
					<div class="row container">
                        <div class="col-md-9" >
						<i class="far fa-play-circle"></i>
						{{link.title}}
						</div>
						<div class="col-md-3">
							<div class="btn-group">
								<a class="btn btn-outline-light" href="#"><i class="fas fa-thumbs-up"></i></a>
								<a class="btn btn-outline-light" href="#"><i class="fas fa-thumbs-down"></i></a>
								<a class="btn btn-outline-light" href="#"><i class="fas fa-trash"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<br/>
			{% endfor %}
			</div>
			<form onSubmit="return addLink();" class="form row border-top" id="add_link_form">
				{% csrf_token %}
				<div class="col-md-9">
					{% bootstrap_form form %}
				</div>
				<div class="col-md-3">
					<br/>
					<button class="btn btn-outline-primary"><i class="fa fa-plus"></i> Ajouter</button>
				</div>
			</form>
		</div>
	</div>
	<div style="display:none;" onclick="setCurrent(parseInt(this.id));" class="card bg-secondary text-white" id="link_template">
				<div class="card-body">
					<div class="row container">
						<div class="col-md-9">
							<i class="far fa-play-circle"></i>
							<span class="link_name"></span>
						</div>
						<div class="col-md-3">
							<div class="btn-group">
								<a class="btn btn-outline-light" href="#"><i class="fas fa-thumbs-up"></i></a>
								<a class="btn btn-outline-light" href="#"><i class="fas fa-thumbs-down"></i></a>
								<a class="btn btn-outline-light" href="#"><i class="fas fa-trash"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>

{% endblock %}

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>LSY{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block js %}{% endblock %}
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="/"><i class="fa fa-users"></i> LSY {% block nav_title %}{% endblock %}</a>
	</nav>
	<main role="main" class="container">
	<br/>
		{% bootstrap_messages %}

		{% block content %}{% endblock %}
	</main>
	<footer class="footer container text-center text-muted">
			LSY by Klafyvel
	</footer>
</body>
</html>

templates/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %} - {{title}}{%endblock%}
{% block content %}
<h3>{{title}}</h3>
<form action="" method="post" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button class="btn btn-outline-primary"><i class="fa fa-star"></i> {{validate}}</button>
</form>
<br>
<br>
<br>
{% endblock %}

templates/form_inline.html
{% load bootstrap4 %}
<form action="" method="post" class="form" id="{{id}}">
	{% csrf_token %}
	{% bootstrap_form form %}
	<button class="btn btn-outline-primary"><i class="fa fa-star"></i> {{validate}}</button>
</form>